const routes = {
    HELLO: 'Hello',
    HOME: 'Home',
    LOGIN: 'Login',
    SIGN_UP: 'SignUp',
    OPTION: 'Option',
    SYMBOL: 'Symbol',
    HOME_STACK: 'HomeStack',
    OPTION_STACK: 'OptionStack',
    FORGOT_PASSWORD: 'ForgotPassword',
    MAIN_NAVIGATION: 'MainNavigation',
    ACOUNT_MANAGEMENT: 'AccountManagement',
    COMMISION: 'Commission',
    DEPOSIT: 'Deposit',
    PROFILE: 'Profile',
    WITHDRAW: 'Withdraw',
    TRANSFER: 'Transfer',
    HISTORY: 'History',
    HISTORY_ADMIN: 'HistoryAdmin',
    DEPOSIT_VND: 'DepositVND',
    HISTORY_DESPOSIT_VND: 'HistoryDespositVND',
    WITHDRAW_VND: 'WithdrawVND',
    HISTORY_WITHDRAW: 'HistoryWithdraw',
    SETTING: 'Setting',
    CHART: 'Chart',
    WALLET: 'Wallet',
    TRADE: 'Trade',
    TRADING: 'Trading',
    PRIZE_POOL: 'PrizePool',
    ORDERS: 'Orders',
    VIPMEMBER: 'Vipmember',
}

export default routes
